export const AboutMyself=[
    { en: "to introduce", ru: "представить себя" },
    { en: "a mother tongue", ru: "родной язык" },
    { en: "to be married / to be single", ru: "быть женатым / быть холостым" },
    { en: "to be on friendly terms with", ru: "быть в дружеских отношениях с" },
    { en: "to get along well with", ru: "хорошо ладить с кем-то" },
    { en: "to have a good sense of humor", ru: "иметь хорошее чувство юмора" },
    { en: "to organize my time wisely (вайзли)", ru: "организовывать время с умом" },
    { en: "to be fond (фонд) of", ru: "любить чем-то заниматься" },
    { en: "to take part in", ru: "принимать участие в" },
    { en: "to do nothing", ru: "ничего не делать" },
    { en: "to spend time", ru: "проводить время" },
    { en: "to go out", ru: "выйти прогуляться / в свет" },
    { en: "to meet new people", ru: "знакомиться с новыми людьми" },
    { en: "to get to know different cultures (колчес)", ru: "узнавать разные культуры" },
    { en: "to discover new ways of life", ru: "открывать новые пути в жизни" },
    { en: "to visit ancient cities", ru: "посещать древние города" },
    { en: "to spend time with friends / at the sea", ru: "проводить время с друзьями / у моря" },
    { en: "to make dreams come true", ru: "осуществить мечты" },
    { en: "to do one’s best", ru: "делать всё возможное" },
    { en: "to lie in the sun", ru: "нежиться на солнце / загорать" },
    { en: "picturesque (пикчьюреск)", ru: "живописный" },
]